use std::{env, fs, path::{Path, PathBuf}};

const FNV_OFFSET: u64 = 0xcbf29ce484222325;
const FNV_PRIME: u64 = 0x100000001b3;
const POLICIES: &str = "framework/policies.toml";

fn main() {
    println!("cargo:rerun-if-changed={POLICIES}");
    println!("cargo:rerun-if-env-changed=HIFI_BUILD_REV");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let policies_path = Path::new(POLICIES);
    let raw = fs::read_to_string(policies_path).expect("read policies.toml");
    let table: toml::Table = raw.parse().expect("parse policies.toml");
    let generated = emit_policies(&table);
    fs::write(out_dir.join("policies_generated.rs"), generated).expect("write policies_generated.rs");

    let mut hash = FNV_OFFSET;
    hash_str(&mut hash, env!("CARGO_PKG_VERSION"));
    if let Ok(rev) = std::env::var("HIFI_BUILD_REV") {
        hash_str(&mut hash, &rev);
    }
    hash_str(&mut hash, &raw);

    println!("cargo:rustc-env=HIFI_BUILD_HASH={hash:016x}");
}

fn emit_policies(table: &toml::Table) -> String {
    let mut out = String::from("// @generated by build.rs from framework/policies.toml\n\n");
    emit_str_array(&mut out, "BAD_EXTS", str_list(table, &["scan", "bad_ext", "exts"]));
    emit_str_array(
        &mut out,
        "ROUTE_BAD_EXTS",
        str_list(table, &["scan", "route_bad_ext", "exts"]),
    );
    emit_str_array(
        &mut out,
        "ASSET_LITERALS",
        str_list(table, &["discover", "assets", "literals"]),
    );
    emit_str_array(
        &mut out,
        "DATA_MARKERS",
        str_list(table, &["discover", "data_markers", "literals"]),
    );
    emit_str_array(
        &mut out,
        "CONTEXT_MARKERS",
        str_list(table, &["discover", "context_markers", "literals"]),
    );
    let context_markers = str_list(table, &["discover", "context_markers", "literals"]);
    let data_markers = str_list(table, &["discover", "data_markers", "literals"]);
    emit_is_context_markers(&mut out, table, "next", "NEXT_IS_CONTEXT_MARKERS", &[], &[]);
    emit_is_context_markers(
        &mut out,
        table,
        "nuxt",
        "NUXT_IS_CONTEXT_MARKERS",
        &context_markers,
        &data_markers,
    );
    emit_is_context_markers(
        &mut out,
        table,
        "sveltekit",
        "SVELTEKIT_IS_CONTEXT_MARKERS",
        &context_markers,
        &data_markers,
    );
    emit_is_context_markers(
        &mut out,
        table,
        "astro",
        "ASTRO_IS_CONTEXT_MARKERS",
        &context_markers,
        &data_markers,
    );
    emit_is_context_markers(
        &mut out,
        table,
        "remix",
        "REMIX_IS_CONTEXT_MARKERS",
        &context_markers,
        &data_markers,
    );
    emit_str_array(
        &mut out,
        "API_PATH_PREFIXES",
        str_list(table, &["scan", "api_paths", "prefixes"]),
    );
    emit_framework_skip(&mut out, "NEXT_SKIP_FRAGMENTS", table, "next");
    emit_framework_skip(&mut out, "NUXT_SKIP_FRAGMENTS", table, "nuxt");
    emit_framework_skip(&mut out, "SVELTEKIT_SKIP_FRAGMENTS", table, "sveltekit");
    emit_framework_skip(&mut out, "ASTRO_SKIP_FRAGMENTS", table, "astro");
    emit_framework_skip(&mut out, "REMIX_SKIP_FRAGMENTS", table, "remix");
    emit_str_array(
        &mut out,
        "NUXT_CONTEXT_PREFIXES",
        str_list(table, &["nuxt", "context_prefixes", "prefixes"]),
    );
    emit_str_array(
        &mut out,
        "SVELTEKIT_CONTEXT_PREFIXES",
        str_list(table, &["sveltekit", "context_prefixes", "prefixes"]),
    );
    emit_str_array(
        &mut out,
        "SVELTEKIT_IMMUTABLE_CHILDREN",
        str_list(table, &["sveltekit", "immutable_children", "paths"]),
    );

    let mut document = Vec::new();
    push_patterns(&mut document, str_list(table, &["scan", "api_call", "literals"]), 0);
    push_patterns(&mut document, str_list(table, &["scan", "api_candidate", "literals"]), 1);
    push_patterns(&mut document, str_list(table, &["scan", "route_call", "literals"]), 2);
    push_patterns(&mut document, str_list(table, &["scan", "route_value", "literals"]), 3);
    push_patterns(&mut document, str_list(table, &["scan", "route_start", "literals"]), 4);
    out.push_str("pub const DOCUMENT_PATTERNS: &[(&str, u8)] = &[\n");
    for (literal, kind) in &document {
        out.push_str(&format!("    ({literal:?}, {kind}),\n"));
    }
    out.push_str("];\n\n");

    let fixed = table
        .get("scan")
        .and_then(|v| v.get("clients"))
        .and_then(|v| v.get("fixed"))
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();
    out.push_str(
        "pub struct FixedClientPattern {\n    pub anchor: &'static [u8],\n    pub method: Option<&'static str>,\n    pub mode: u8,\n}\n\n",
    );
    out.push_str("pub const FIXED_CLIENT_PATTERNS: &[FixedClientPattern] = &[\n");
    for entry in fixed {
        let Some(row) = entry.as_table() else { continue };
        let anchor = row
            .get("anchor")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let mode = row
            .get("mode")
            .and_then(|v| v.as_str())
            .map(client_mode)
            .unwrap_or(0);
        let method = row
            .get("method")
            .and_then(|v| v.as_str())
            .map(|m| format!("Some({m:?})"))
            .unwrap_or_else(|| "None".to_string());
        out.push_str(&format!(
            "    FixedClientPattern {{ anchor: {anchor:?}.as_bytes(), method: {method}, mode: {mode} }},\n"
        ));
    }
    emit_client_method_patterns(&mut out, table);
    out.push_str("];\n");
    out
}

fn emit_framework_skip(out: &mut String, name: &str, table: &toml::Table, framework: &str) {
    emit_str_array(out, name, str_list(table, &[framework, "skip", "fragments"]));
}

fn emit_is_context_markers(
    out: &mut String,
    table: &toml::Table,
    framework: &str,
    name: &str,
    context_markers: &[String],
    data_markers: &[String],
) {
    let section = table.get(framework).and_then(|v| v.get("is_context"));
    let mut items = Vec::new();
    if let Some(section) = section.and_then(|v| v.as_table()) {
        for literal in str_list_in(section, &["context"]) {
            assert!(
                context_markers.contains(&literal),
                "{framework}.is_context.context literal {literal:?} missing from discover.context_markers"
            );
            items.push(literal);
        }
        for literal in str_list_in(section, &["data"]) {
            assert!(
                data_markers.contains(&literal),
                "{framework}.is_context.data literal {literal:?} missing from discover.data_markers"
            );
            items.push(literal);
        }
        items.extend(str_list_in(section, &["extra"]));
    }
    emit_str_array(out, name, items);
}

fn str_list_in(table: &toml::Table, path: &[&str]) -> Vec<String> {
    let mut value = toml::Value::Table(table.clone());
    for key in path {
        let Some(next) = value.get(*key) else {
            return Vec::new();
        };
        value = next.clone();
    }
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|v| v.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default()
}

fn emit_client_method_patterns(out: &mut String, table: &toml::Table) {
    let methods = str_list(table, &["scan", "clients", "methods", "verbs"]);
    let templates = str_list(table, &["scan", "clients", "method_templates", "patterns"]);
    let modes = table
        .get("scan")
        .and_then(|v| v.get("clients"))
        .and_then(|v| v.get("method_templates"))
        .and_then(|v| v.get("modes"))
        .and_then(|v| v.as_array())
        .map(|items| {
            items
                .iter()
                .filter_map(|v| v.as_str().map(str::to_owned))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    for method in methods {
        let lower = method.to_ascii_lowercase();
        for (idx, template) in templates.iter().enumerate() {
            let anchor = template
                .replace("{method}", &lower)
                .replace("${method}", &lower);
            let mode = modes
                .get(idx)
                .map(|name| client_mode(name))
                .unwrap_or(0);
            let method_ref = format!("Some({method:?})");
            out.push_str(&format!(
                "    FixedClientPattern {{ anchor: {anchor:?}.as_bytes(), method: {method_ref}, mode: {mode} }},\n"
            ));
        }
    }
}

fn client_mode(name: &str) -> u8 {
    match name {
        "first_arg" => 0,
        "object" => 1,
        "generic_method" => 2,
        _ => 0,
    }
}

fn push_patterns(out: &mut Vec<(String, u8)>, literals: Vec<String>, kind: u8) {
    for literal in literals {
        out.push((literal, kind));
    }
}

fn emit_str_array(out: &mut String, name: &str, items: Vec<String>) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for item in items {
        out.push_str(&format!("    {item:?},\n"));
    }
    out.push_str("];\n\n");
}

fn str_list(table: &toml::Table, path: &[&str]) -> Vec<String> {
    let mut value = toml::Value::Table(table.clone());
    for key in path {
        let Some(next) = value.get(*key) else {
            return Vec::new();
        };
        value = next.clone();
    }
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|v| v.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default()
}

fn hash_str(hash: &mut u64, value: &str) {
    hash_bytes(hash, value.as_bytes());
}

fn hash_bytes(hash: &mut u64, bytes: &[u8]) {
    for byte in bytes {
        *hash ^= *byte as u64;
        *hash = hash.wrapping_mul(FNV_PRIME);
    }
    *hash ^= b'\n' as u64;
    *hash = hash.wrapping_mul(FNV_PRIME);
}
