use std::{env, fs, path::{Path, PathBuf}};

const FNV_OFFSET: u64 = 0xcbf29ce484222325;
const FNV_PRIME: u64 = 0x100000001b3;
const POLICIES: &str = "framework/policies.toml";

fn main() {
    println!("cargo:rerun-if-changed={POLICIES}");
    println!("cargo:rerun-if-env-changed=HIFI_BUILD_REV");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let policies_path = Path::new(POLICIES);
    let raw = fs::read_to_string(policies_path).expect("read policies.toml");
    let table: toml::Table = raw.parse().expect("parse policies.toml");
    let generated = emit_policies(&table);
    fs::write(out_dir.join("policies_generated.rs"), generated).expect("write policies_generated.rs");

    let mut hash = FNV_OFFSET;
    hash_str(&mut hash, env!("CARGO_PKG_VERSION"));
    if let Ok(rev) = std::env::var("HIFI_BUILD_REV") {
        hash_str(&mut hash, &rev);
    } else {
        hash_git_head(&mut hash);
    }

    for path in build_inputs() {
        println!("cargo:rerun-if-changed={}", path.display());
        hash_str(&mut hash, &path.display().to_string());
        if let Ok(bytes) = fs::read(&path) {
            hash_bytes(&mut hash, &bytes);
        }
    }
    hash_str(&mut hash, &raw);

    println!("cargo:rustc-env=HIFI_BUILD_HASH={hash:016x}");
}

fn emit_policies(table: &toml::Table) -> String {
    let mut out = String::from("// @generated by build.rs from framework/policies.toml\n\n");
    emit_str_array(&mut out, "BAD_EXTS", str_list(table, &["scan", "bad_ext", "exts"]));
    emit_str_array(
        &mut out,
        "ROUTE_BAD_EXTS",
        str_list(table, &["scan", "route_bad_ext", "exts"]),
    );
    emit_str_array(
        &mut out,
        "ASSET_LITERALS",
        str_list(table, &["discover", "assets", "literals"]),
    );
    emit_str_array(
        &mut out,
        "DATA_MARKERS",
        str_list(table, &["discover", "data_markers", "literals"]),
    );
    emit_str_array(
        &mut out,
        "CLIENT_METHODS",
        str_list(table, &["scan", "clients", "methods", "verbs"]),
    );

    let mut document = Vec::new();
    push_patterns(&mut document, str_list(table, &["scan", "api_call", "literals"]), 0);
    push_patterns(&mut document, str_list(table, &["scan", "api_candidate", "literals"]), 1);
    push_patterns(&mut document, str_list(table, &["scan", "route_call", "literals"]), 2);
    push_patterns(&mut document, str_list(table, &["scan", "route_value", "literals"]), 3);
    push_patterns(&mut document, str_list(table, &["scan", "route_start", "literals"]), 4);
    out.push_str("pub const DOCUMENT_PATTERNS: &[(&str, u8)] = &[\n");
    for (literal, kind) in &document {
        out.push_str(&format!("    ({literal:?}, {kind}),\n"));
    }
    out.push_str("];\n\n");

    let fixed = table
        .get("scan")
        .and_then(|v| v.get("clients"))
        .and_then(|v| v.get("fixed"))
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();
    out.push_str(
        "pub struct FixedClientPattern {\n    pub anchor: &'static [u8],\n    pub method: Option<&'static str>,\n    pub mode: u8,\n}\n\n",
    );
    out.push_str("pub const FIXED_CLIENT_PATTERNS: &[FixedClientPattern] = &[\n");
    for entry in fixed {
        let Some(row) = entry.as_table() else { continue };
        let anchor = row
            .get("anchor")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let mode = row
            .get("mode")
            .and_then(|v| v.as_str())
            .map(client_mode)
            .unwrap_or(0);
        let method = row
            .get("method")
            .and_then(|v| v.as_str())
            .map(|m| format!("Some({m:?})"))
            .unwrap_or_else(|| "None".to_string());
        out.push_str(&format!(
            "    FixedClientPattern {{ anchor: {anchor:?}.as_bytes(), method: {method}, mode: {mode} }},\n"
        ));
    }
    out.push_str("];\n");
    out
}

fn client_mode(name: &str) -> u8 {
    match name {
        "first_arg" => 0,
        "object" => 1,
        "generic_method" => 2,
        _ => 0,
    }
}

fn push_patterns(out: &mut Vec<(String, u8)>, literals: Vec<String>, kind: u8) {
    for literal in literals {
        out.push((literal, kind));
    }
}

fn emit_str_array(out: &mut String, name: &str, items: Vec<String>) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for item in items {
        out.push_str(&format!("    {item:?},\n"));
    }
    out.push_str("];\n\n");
}

fn str_list(table: &toml::Table, path: &[&str]) -> Vec<String> {
    let mut value = toml::Value::Table(table.clone());
    for key in path {
        let Some(next) = value.get(*key) else {
            return Vec::new();
        };
        value = next.clone();
    }
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|v| v.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default()
}

fn build_inputs() -> Vec<PathBuf> {
    let mut paths = vec![
        PathBuf::from("Cargo.toml"),
        PathBuf::from("Cargo.lock"),
        PathBuf::from("build.rs"),
        PathBuf::from(POLICIES),
    ];
    collect_rs_files(Path::new("src"), &mut paths);
    paths.sort();
    paths
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs_files(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

fn hash_git_head(hash: &mut u64) {
    let head_path = Path::new(".git/HEAD");
    println!("cargo:rerun-if-changed={}", head_path.display());
    let Ok(head) = fs::read_to_string(head_path) else {
        return;
    };
    hash_str(hash, head.trim());
    if let Some(reference) = head.trim().strip_prefix("ref: ") {
        let ref_path = Path::new(".git").join(reference);
        println!("cargo:rerun-if-changed={}", ref_path.display());
        if let Ok(value) = fs::read_to_string(ref_path) {
            hash_str(hash, value.trim());
        }
    }
}

fn hash_str(hash: &mut u64, value: &str) {
    hash_bytes(hash, value.as_bytes());
}

fn hash_bytes(hash: &mut u64, bytes: &[u8]) {
    for byte in bytes {
        *hash ^= *byte as u64;
        *hash = hash.wrapping_mul(FNV_PRIME);
    }
    *hash ^= b'\n' as u64;
    *hash = hash.wrapping_mul(FNV_PRIME);
}
