pub const CALL_LITERALS: &[&str] = &[
    "fetch(",
    "fetch (",
    ".fetch(",
    "axios(",
    "axios.get(",
    "axios.post(",
    "axios.put(",
    "axios.delete(",
    "axios.patch(",
    "axios.request(",
    "$fetch(",
    "ofetch(",
    "ky.get(",
    "ky.post(",
    "ky(",
    "got(",
    "request(",
    "url:\"",
    "url:'",
    "url: \"",
    "url: '",
    "endpoint:\"",
    "endpoint:'",
    ".get(",
    ".post(",
    ".put(",
    ".delete(",
    ".patch(",
    "useSWR(",
    "useSWRMutation(",
    "useSWRInfinite(",
    "new Request(",
];

pub const SHAPE_LITERALS: &[&str] = &[
    "method:\"POST\"",
    "method:'POST'",
    "method: \"POST\"",
    "method: 'POST'",
    "method:\"post\"",
    "method:'post'",
    "method: \"post\"",
    "method: 'post'",
    "method:\"PUT\"",
    "method:'PUT'",
    "method: \"PUT\"",
    "method: 'PUT'",
    "method:\"put\"",
    "method:'put'",
    "method: \"put\"",
    "method: 'put'",
    "method:\"DELETE\"",
    "method:'DELETE'",
    "method: \"DELETE\"",
    "method: 'DELETE'",
    "method:\"delete\"",
    "method:'delete'",
    "method: \"delete\"",
    "method: 'delete'",
    "method:\"PATCH\"",
    "method:'PATCH'",
    "method: \"PATCH\"",
    "method: 'PATCH'",
    "method:\"patch\"",
    "method:'patch'",
    "method: \"patch\"",
    "method: 'patch'",
    "method:\"GET\"",
    "method:'GET'",
    "method: \"GET\"",
    "method: 'GET'",
    "method:\"get\"",
    "method:'get'",
    "method: \"get\"",
    "method: 'get'",
    "method:\"HEAD\"",
    "method:'HEAD'",
    "method: \"HEAD\"",
    "method: 'HEAD'",
    "method:\"head\"",
    "method:'head'",
    "method: \"head\"",
    "method: 'head'",
    "method:\"OPTIONS\"",
    "method:'OPTIONS'",
    "method: \"OPTIONS\"",
    "method: 'OPTIONS'",
    "method:\"options\"",
    "method:'options'",
    "method: \"options\"",
    "method: 'options'",
    "body:",
    "body: ",
    "body :",
    "headers:",
    "headers: ",
    "headers :",
    "Content-Type",
    "content-type",
    "application/json",
    "multipart/form-data",
    "application/x-www-form-urlencoded",
    "text/plain",
    "Authorization",
    "authorization",
    "Bearer",
    "FormData(",
    "URLSearchParams(",
];

pub const ROUTE_CALL_LITERALS: &[&str] = &[
    "router.push(",
    "router.replace(",
    "router.prefetch(",
    ".push(",
    ".replace(",
    ".prefetch(",
    "navigate(",
];

pub const ROUTE_VALUE_LITERALS: &[&str] = &["href", "pathname", "asPath", "action", "formAction"];

pub const ROUTE_START_LITERALS: &[&str] = &["\"/", "'/", "`/", "\\\"/", "\\'/"];

pub const ROUTE_BAD_EXTS: &[&str] = &[
    ".js", ".css", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".woff", ".woff2", ".ttf", ".ico",
    ".webp", ".mp4", ".webm", ".map", ".json", ".txt", ".xml",
];

pub const BAD_EXTS: &[&str] = &[
    ".js", ".css", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".woff", ".woff2", ".ttf", ".ico",
    ".webp", ".mp4", ".webm", ".map",
];

pub const SKIPPED_CHUNK_FRAGMENTS: &[&str] = &[
    // webpack runtime / shared chunks
    "framework-",
    "polyfills-",
    "webpack-",
    "main-",
    "main-app-",
    // turbopack runtime chunks (Next 15+)
    "_next/static/chunks/_turbopack_",
    "[turbopack]_runtime",
    "[next]_internal_",
    // react / next shared vendor chunks
    "react-refresh",
    "next/dist/",
];
